import type { Metadata } from "next";
import localFont from "next/font/local";
import Script from "next/script";

import "./globals.css";
import { ThemeProvider } from "./provider";

export const metadata: Metadata = {
  title: "CollabEZ- Let's Create Extraordinary",
  description: "Generated by create next app",
};

const satoshiRegular = localFont({
  src: "./fonts/Satoshi-Regular.otf",
  variable: "--font-satoshi",
  weight: "100 900",
});
const satoshiBold = localFont({
  src: "./fonts/Satoshi-Regular.otf",
  variable: "--font-satoshi-bold",
  weight: "100 900",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/favicon.png" sizes="any" />

        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-SNJ9FJ8VQT"
        />

        {/* Initialize Google Analytics */}
        <Script
          id="google-analytics"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-SNJ9FJ8VQT');
            `,
          }}
        />
      </head>
      <body className={`${satoshiRegular.variable} ${satoshiBold.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
